spring.application.name=Food_Ordering_App

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:food_ordering_app}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false
spring.jpa.open-in-view=false

spring.sql.init.mode=always

app.mail.enabled=false
app.mail.from=no-reply@foodapp.local
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
