spring.datasource.url=jdbc:postgresql://localhost:5432/food_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

email.enabled=false
server.port=8080
